version: '3'
services:
  app:
    build: .
    container_name: tour-app
    environment:
      - DATABASE_URL=postgresql://postgres:postgre@db:5432/postgres
      - JWT_SECRET=3mk
      - NODE_ENV=development
      - PORT=6969
    ports:
      - "6969:6969"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:13-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgre
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
